In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
independent=dataset[['age', 'bmi', 'children','sex_male','smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [6]:
dependent=dataset[["charges"]]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.3,random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler 
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression
param_grid = {
    'fit_intercept': [True, False],
    'copy_X': [True, False],
    'n_jobs': [None, 1, -1],
    'positive': [False, True]
}
grid=GridSearchCV(LinearRegression(), param_grid, refit=True, verbose=3, n_jobs=-1)
grid.fit(x_train,y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

GridSearchCV(estimator=LinearRegression(), n_jobs=-1,
             param_grid={'copy_X': [True, False],
                         'fit_intercept': [True, False],
                         'n_jobs': [None, 1, -1], 'positive': [False, True]},
             verbose=3)

In [21]:
best_model = grid.best_estimator_

In [22]:
y_pred = best_model.predict(independent)

C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\base.py:457: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(

In [23]:
re=grid.cv_results_
print=("best_parametes{}:".format(grid.best_params_))

In [24]:
print

"best_parametes{'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'positive': True}:"

In [25]:
table=pd.DataFrame.from_dict(re)

In [26]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_copy_X,param_fit_intercept,param_n_jobs,param_positive,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.062038,0.018054,0.002305,0.004610,True,True,None,False,"{'copy_X': True, 'fit_intercept': True, 'n_job...",0.763511,0.702938,0.730655,0.695551,0.719087,0.722348,0.023954,7
1,0.010803,0.006498,0.003803,0.004658,True,True,None,True,"{'copy_X': True, 'fit_intercept': True, 'n_job...",0.763511,0.703146,0.730655,0.695634,0.719080,0.722405,0.023902,1
2,0.064962,0.013196,0.003124,0.006248,True,True,1,False,"{'copy_X': True, 'fit_intercept': True, 'n_job...",0.763511,0.702938,0.730655,0.695551,0.719087,0.722348,0.023954,7
3,0.000000,0.000000,0.000000,0.000000,True,True,1,True,"{'copy_X': True, 'fit_intercept': True, 'n_job...",0.763511,0.703146,0.730655,0.695634,0.719080,0.722405,0.023902,1
4,0.022032,0.021380,0.000000,0.000000,True,True,-1,False,"{'copy_X': True, 'fit_intercept': True, 'n_job...",0.763511,0.702938,0.730655,0.695551,0.719087,0.722348,0.023954,7
5,0.029166,0.011007,0.005603,0.006862,True,True,-1,True,"{'copy_X': True, 'fit_intercept': True, 'n_job...",0.763511,0.703146,0.730655,0.695634,0.719080,0.722405,0.023902,1
6,0.006652,0.007362,0.000403,0.000806,True,False,None,False,"{'copy_X': True, 'fit_intercept': False, 'n_jo...",-0.698095,-0.586805,-0.459207,-0.600488,-0.419146,-0.552748,0.101157,19
7,0.000000,0.000000,0.000000,0.000000,True,False,None,True,"{'copy_X': True, 'fit_intercept': False, 'n_jo...",-0.698095,-0.586653,-0.459207,-0.598656,-0.416113,-0.551745,0.101781,13
8,0.008404,0.006862,0.002801,0.005603,True,False,1,False,"{'copy_X': True, 'fit_intercept': False, 'n_jo...",-0.698095,-0.586805,-0.459207,-0.600488,-0.419146,-0.552748,0.101157,19
9,0.000000,0.000000,0.000000,0.000000,True,False,1,True,"{'copy_X': True, 'fit_intercept': False, 'n_jo...",-0.698095,-0.586653,-0.459207,-0.598656,-0.416113,-0.551745,0.101781,13
10,0.000000,0.000000,0.003127,0.006253,True,False,-1,False,"{'copy_X': True, 'fit_intercept': False, 'n_jo...",-0.698095,-0.586805,-0.459207,-0.600488,-0.419146,-0.552748,0.101157,19
11,0.021297,0.006937,0.000925,0.001176,True,False,-1,True,"{'copy_X': True, 'fit_intercept': False, 'n_jo...",-0.698095,-0.586653,-0.459207,-0.598656,-0.416113,-0.551745,0.101781,13
12,0.002271,0.004542,0.002564,0.004643,False,True,None,False,"{'copy_X': False, 'fit_intercept': True, 'n_jo...",0.763511,0.702938,0.730655,0.695551,0.719087,0.722348,0.023954,7
13,0.008336,0.005141,0.001800,0.000156,False,True,None,True,"{'copy_X': False, 'fit_intercept': True, 'n_jo...",0.763511,0.703146,0.730655,0.695634,0.719080,0.722405,0.023902,1
14,0.002409,0.000618,0.001115,0.000234,False,True,1,False,"{'copy_X': False, 'fit_intercept': True, 'n_jo...",0.763511,0.702938,0.730655,0.695551,0.719087,0.722348,0.023954,7
15,0.002183,0.000461,0.001321,0.000412,False,True,1,True,"{'copy_X': False, 'fit_intercept': True, 'n_jo...",0.763511,0.703146,0.730655,0.695634,0.719080,0.722405,0.023902,1
16,0.002111,0.000667,0.001464,0.000574,False,True,-1,False,"{'copy_X': False, 'fit_intercept': True, 'n_jo...",0.763511,0.702938,0.730655,0.695551,0.719087,0.722348,0.023954,7
17,0.010178,0.002510,0.001916,0.000654,False,True,-1,True,"{'copy_X': False, 'fit_intercept': True, 'n_jo...",0.763511,0.703146,0.730655,0.695634,0.719080,0.722405,0.023902,1
18,0.002109,0.000210,0.001372,0.000641,False,False,None,False,"{'copy_X': False, 'fit_intercept': False, 'n_j...",-0.698095,-0.586805,-0.459207,-0.600488,-0.419146,-0.552748,0.101157,19
19,0.002938,0.000751,0.001672,0.000680,False,False,None,True,"{'copy_X': False, 'fit_intercept': False, 'n_j...",-0.698095,-0.586653,-0.459207,-0.598656,-0.416113,-0.551745,0.101781,13
20,0.002518,0.000587,0.001402,0.000401,False,False,1,False,"{'copy_X': False, 'fit_intercept': False, 'n_j...",-0.698095,-0.586805,-0.459207,-0.600488,-0.419146,-0.552748,0.101157,19
21,0.003076,0.000593,0.001354,0.000216,False,False,1,True,"{'copy_X': False, 'fit_intercept': False, 'n_j...",-0.698095,-0.586653,-0.459207,-0.598656,-0.416113,-0.551745,0.101781,13
22,0.002584,0.000514,0.001424,0.000333,False,False,-1,False,"{'copy_X': False, 'fit_intercept': False, 'n_j...",-0.698095,-0.586805,-0.459207,-0.600488,-0.419146,-0.552748,0.101157,19
23,0.006248,0.002760,0.000829,0.000775,False,False,-1,True,"{'copy_X': False, 'fit_intercept': False, 'n_j...",-0.698095,-0.586653,-0.459207,-0.598656,-0.416113,-0.551745,0.101781,13

In [27]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:32
BMI:28
Children:2
Sex Male 0 or 1:0
Smoker Yes 0 or 1:1

In [28]:
Future_prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])

In [29]:
print=("Future_prediction={}",format(Future_prediction))

In [30]:
print

('Future_prediction={}', '[[195337.50676728]]')

In [31]:
from sklearn.metrics import r2_score
r_score=r2_score(dependent,y_pred)
r_score

-304.0858589287166