In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
independent=dataset[['age', 'bmi', 'children','sex_male','smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [6]:
dependent=dataset[["charges"]]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [7]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression
param_grid = {
    'fit_intercept': [True, False],
    'copy_X': [True, False],
    'n_jobs': [None, 1, -1],
    'positive': [False, True]
}
grid=GridSearchCV(LinearRegression(), param_grid, refit=True, verbose=3, n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

GridSearchCV(estimator=LinearRegression(), n_jobs=-1,
             param_grid={'copy_X': [True, False],
                         'fit_intercept': [True, False],
                         'n_jobs': [None, 1, -1], 'positive': [False, True]},
             verbose=3)

In [22]:
best_model = grid.best_estimator_

In [19]:
y_pred = best_model.predict(independent)

In [24]:
from sklearn.metrics import r2_score
r_score = r2_score(dependent, y_pred)

In [25]:
re=grid.cv_results_
print=("best_parametes{}:".format(grid.best_params_))

In [26]:
print

"best_parametes{'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'positive': True}:"

In [27]:
table=pd.DataFrame.from_dict(re)

In [28]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_copy_X,param_fit_intercept,param_n_jobs,param_positive,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.069566,0.008145,0.002625,0.003471,True,True,None,False,"{'copy_X': True, 'fit_intercept': True, 'n_job...",0.760979,0.708733,0.775584,0.731367,0.756545,0.746642,0.023713,7
1,0.011009,0.010055,0.003643,0.004568,True,True,None,True,"{'copy_X': True, 'fit_intercept': True, 'n_job...",0.761482,0.708782,0.775584,0.731353,0.756751,0.746790,0.023778,1
2,0.054419,0.011850,0.003877,0.005499,True,True,1,False,"{'copy_X': True, 'fit_intercept': True, 'n_job...",0.760979,0.708733,0.775584,0.731367,0.756545,0.746642,0.023713,7
3,0.005784,0.005467,0.006257,0.004282,True,True,1,True,"{'copy_X': True, 'fit_intercept': True, 'n_job...",0.761482,0.708782,0.775584,0.731353,0.756751,0.746790,0.023778,1
4,0.013115,0.012626,0.002534,0.001530,True,True,-1,False,"{'copy_X': True, 'fit_intercept': True, 'n_job...",0.760979,0.708733,0.775584,0.731367,0.756545,0.746642,0.023713,7
5,0.021732,0.005534,0.004675,0.003297,True,True,-1,True,"{'copy_X': True, 'fit_intercept': True, 'n_job...",0.761482,0.708782,0.775584,0.731353,0.756751,0.746790,0.023778,1
6,0.015237,0.017331,0.004181,0.002919,True,False,None,False,"{'copy_X': True, 'fit_intercept': False, 'n_jo...",0.727683,0.691272,0.738275,0.700259,0.727085,0.716915,0.017948,13
7,0.004406,0.000346,0.003138,0.000378,True,False,None,True,"{'copy_X': True, 'fit_intercept': False, 'n_jo...",0.727280,0.691876,0.735943,0.699020,0.729543,0.716732,0.017754,19
8,0.004806,0.000561,0.002776,0.000514,True,False,1,False,"{'copy_X': True, 'fit_intercept': False, 'n_jo...",0.727683,0.691272,0.738275,0.700259,0.727085,0.716915,0.017948,13
9,0.004194,0.000941,0.000959,0.001202,True,False,1,True,"{'copy_X': True, 'fit_intercept': False, 'n_jo...",0.727280,0.691876,0.735943,0.699020,0.729543,0.716732,0.017754,19
10,0.000162,0.000324,0.000000,0.000000,True,False,-1,False,"{'copy_X': True, 'fit_intercept': False, 'n_jo...",0.727683,0.691272,0.738275,0.700259,0.727085,0.716915,0.017948,13
11,0.015007,0.000000,0.003159,0.006318,True,False,-1,True,"{'copy_X': True, 'fit_intercept': False, 'n_jo...",0.727280,0.691876,0.735943,0.699020,0.729543,0.716732,0.017754,19
12,0.003001,0.006003,0.012005,0.006003,False,True,None,False,"{'copy_X': False, 'fit_intercept': True, 'n_jo...",0.760979,0.708733,0.775584,0.731367,0.756545,0.746642,0.023713,7
13,0.003001,0.006003,0.000000,0.000000,False,True,None,True,"{'copy_X': False, 'fit_intercept': True, 'n_jo...",0.761482,0.708782,0.775584,0.731353,0.756751,0.746790,0.023778,1
14,0.000000,0.000000,0.009476,0.007737,False,True,1,False,"{'copy_X': False, 'fit_intercept': True, 'n_jo...",0.760979,0.708733,0.775584,0.731367,0.756545,0.746642,0.023713,7
15,0.003159,0.006318,0.003159,0.006318,False,True,1,True,"{'copy_X': False, 'fit_intercept': True, 'n_jo...",0.761482,0.708782,0.775584,0.731353,0.756751,0.746790,0.023778,1
16,0.009476,0.007737,0.000000,0.000000,False,True,-1,False,"{'copy_X': False, 'fit_intercept': True, 'n_jo...",0.760979,0.708733,0.775584,0.731367,0.756545,0.746642,0.023713,7
17,0.018788,0.006319,0.000000,0.000000,False,True,-1,True,"{'copy_X': False, 'fit_intercept': True, 'n_jo...",0.761482,0.708782,0.775584,0.731353,0.756751,0.746790,0.023778,1
18,0.003126,0.006253,0.000000,0.000000,False,False,None,False,"{'copy_X': False, 'fit_intercept': False, 'n_j...",0.727683,0.691272,0.738275,0.700259,0.727085,0.716915,0.017948,13
19,0.009379,0.007658,0.000000,0.000000,False,False,None,True,"{'copy_X': False, 'fit_intercept': False, 'n_j...",0.727280,0.691876,0.735943,0.699020,0.729543,0.716732,0.017754,19
20,0.006253,0.007658,0.000000,0.000000,False,False,1,False,"{'copy_X': False, 'fit_intercept': False, 'n_j...",0.727683,0.691272,0.738275,0.700259,0.727085,0.716915,0.017948,13
21,0.000000,0.000000,0.009374,0.007654,False,False,1,True,"{'copy_X': False, 'fit_intercept': False, 'n_j...",0.727280,0.691876,0.735943,0.699020,0.729543,0.716732,0.017754,19
22,0.006250,0.007654,0.003125,0.006250,False,False,-1,False,"{'copy_X': False, 'fit_intercept': False, 'n_j...",0.727683,0.691272,0.738275,0.700259,0.727085,0.716915,0.017948,13
23,0.003125,0.006250,0.006280,0.007691,False,False,-1,True,"{'copy_X': False, 'fit_intercept': False, 'n_j...",0.727280,0.691876,0.735943,0.699020,0.729543,0.716732,0.017754,19

In [29]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:32
BMI:28
Children:3
Sex Male 0 or 1:1
Smoker Yes 0 or 1:0

In [30]:
Future_prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])

C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [31]:
print=("Future_prediction={}",format(Future_prediction))

In [32]:
print

('Future_prediction={}', '[[6580.76108599]]')

In [33]:
from sklearn.metrics import r2_score
r_score=r2_score(dependent,y_pred)
r_score

0.749694530346479