In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [4]:

dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
indep

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [6]:
depn=dataset[["charges"]]
depn

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep,depn,test_size=0.3,random_state=0)

In [8]:
from sklearn.preprocessing import StandardScaler 
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [9]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV 
param_grid={'criterion':["squared error","friedman_mse","absolute error","poisson"],'max_features':['None','sqrt','log2'],'n_estimators':[10,50,100]}
grid=GridSearchCV(RandomForestRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)

In [10]:
grid.fit(x_train,y_train)

Fitting 5 folds for each of 36 candidates, totalling 180 fits

C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning:
120 fits failed out of a total of 180.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
8 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'squared_error', 'poisson', 'absolute_error', 'friedman_mse'}. Got 'squared error' instead.

--------------------------------------------------------------------------------
2 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'squared_error', 'absolute_error', 'poisson', 'friedman_mse'}. Got 'squared error' instead.

--------------------------------------------------------------------------------
4 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'poisson', 'squared_error', 'absolute_error', 'friedman_mse'}. Got 'squared error' instead.

--------------------------------------------------------------------------------
4 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'absolute_error', 'friedman_mse', 'squared_error', 'poisson'}. Got 'squared error' instead.

--------------------------------------------------------------------------------
4 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'squared_error', 'poisson', 'friedman_mse', 'absolute_error'}. Got 'squared error' instead.

--------------------------------------------------------------------------------
7 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'poisson', 'squared_error', 'friedman_mse', 'absolute_error'}. Got 'squared error' instead.

--------------------------------------------------------------------------------
4 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'absolute_error', 'poisson', 'friedman_mse', 'squared_error'}. Got 'squared error' instead.

--------------------------------------------------------------------------------
8 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'absolute_error', 'poisson', 'squared_error', 'friedman_mse'}. Got 'squared error' instead.

--------------------------------------------------------------------------------
4 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'squared_error', 'absolute_error', 'poisson'}. Got 'squared error' instead.

--------------------------------------------------------------------------------
13 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'None' instead.

--------------------------------------------------------------------------------
17 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'None' instead.

--------------------------------------------------------------------------------
12 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'poisson', 'squared_error', 'friedman_mse', 'absolute_error'}. Got 'absolute error' instead.

--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'poisson', 'squared_error', 'absolute_error', 'friedman_mse'}. Got 'absolute error' instead.

--------------------------------------------------------------------------------
18 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'absolute_error', 'poisson', 'friedman_mse', 'squared_error'}. Got 'absolute error' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:976: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.78348044 0.80820252 0.81297801 0.79586525 0.81146398 0.81007594
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.78861128 0.81279861 0.8113628  0.78941876 0.81049646 0.81103524]
  warnings.warn(
C:\Users\Malya\anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared error', 'friedman_mse',
                                       'absolute error', 'poisson'],
                         'max_features': ['None', 'sqrt', 'log2'],
                         'n_estimators': [10, 50, 100]},
             verbose=3)

In [11]:
GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ["squared error","friedman_mse","absolute error","poisson"],
                         'max_features': ['None', 'sqrt', 'log2'],
                         'n_estimators': [10, 50,100]},
             verbose=3)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared error', 'friedman_mse',
                                       'absolute error', 'poisson'],
                         'max_features': ['None', 'sqrt', 'log2'],
                         'n_estimators': [10, 50, 100]},
             verbose=3)

In [12]:
re=grid.cv_results_
print=("best_parameter{}:".format(grid.best_params_))

In [13]:
print

"best_parameter{'criterion': 'friedman_mse', 'max_features': 'sqrt', 'n_estimators': 100}:"

In [14]:
 table=pd.DataFrame.from_dict(re)

In [15]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005782,0.004249,0.000000,0.000000,squared error,None,10,"{'criterion': 'squared error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
1,0.003603,0.004413,0.000000,0.000000,squared error,None,50,"{'criterion': 'squared error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
2,0.003158,0.005225,0.000000,0.000000,squared error,None,100,"{'criterion': 'squared error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
3,0.000761,0.000270,0.000000,0.000000,squared error,sqrt,10,"{'criterion': 'squared error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
4,0.000310,0.000414,0.000000,0.000000,squared error,sqrt,50,"{'criterion': 'squared error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
5,0.001411,0.000952,0.000000,0.000000,squared error,sqrt,100,"{'criterion': 'squared error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
6,0.000606,0.000078,0.000000,0.000000,squared error,log2,10,"{'criterion': 'squared error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
7,0.000477,0.000262,0.000000,0.000000,squared error,log2,50,"{'criterion': 'squared error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
8,0.000677,0.000117,0.000000,0.000000,squared error,log2,100,"{'criterion': 'squared error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
9,0.000522,0.000324,0.000000,0.000000,friedman_mse,None,10,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
10,0.000588,0.000676,0.000000,0.000000,friedman_mse,None,50,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
11,0.000122,0.000244,0.000000,0.000000,friedman_mse,None,100,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
12,0.028895,0.001556,0.003124,0.006249,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.832927,0.769806,0.784357,0.801850,0.728462,0.783480,0.034633,12
13,0.168669,0.009521,0.006203,0.007597,friedman_mse,sqrt,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.857137,0.789358,0.804066,0.823027,0.767426,0.808203,0.030494,8
14,0.367151,0.007947,0.010480,0.008050,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.864247,0.793642,0.811864,0.827536,0.767601,0.812978,0.032480,1
15,0.049229,0.017684,0.000000,0.000000,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.833786,0.777412,0.795337,0.808794,0.763998,0.795865,0.024337,9
16,0.193847,0.008190,0.000612,0.001223,friedman_mse,log2,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.861956,0.794590,0.816024,0.825166,0.759585,0.811464,0.033865,3
17,0.353673,0.012349,0.012669,0.003754,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.863397,0.791366,0.807772,0.822749,0.765095,0.810076,0.032810,7
18,0.000000,0.000000,0.000000,0.000000,absolute error,None,10,"{'criterion': 'absolute error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
19,0.000000,0.000000,0.000000,0.000000,absolute error,None,50,"{'criterion': 'absolute error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
20,0.000000,0.000000,0.000000,0.000000,absolute error,None,100,"{'criterion': 'absolute error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
21,0.000000,0.000000,0.000000,0.000000,absolute error,sqrt,10,"{'criterion': 'absolute error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
22,0.000000,0.000000,0.000000,0.000000,absolute error,sqrt,50,"{'criterion': 'absolute error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
23,0.000000,0.000000,0.000000,0.000000,absolute error,sqrt,100,"{'criterion': 'absolute error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
24,0.003126,0.006252,0.000000,0.000000,absolute error,log2,10,"{'criterion': 'absolute error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
25,0.000000,0.000000,0.000000,0.000000,absolute error,log2,50,"{'criterion': 'absolute error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
26,0.003125,0.006250,0.000000,0.000000,absolute error,log2,100,"{'criterion': 'absolute error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
27,0.000000,0.000000,0.000000,0.000000,poisson,None,10,"{'criterion': 'poisson', 'max_features': 'None...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
28,0.000000,0.000000,0.000000,0.000000,poisson,None,50,"{'criterion': 'poisson', 'max_features': 'None...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
29,0.000000,0.000000,0.000000,0.000000,poisson,None,100,"{'criterion': 'poisson', 'max_features': 'None...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
30,0.043395,0.005752,0.004378,0.006088,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.824535,0.771707,0.797765,0.808187,0.740862,0.788611,0.029405,11
31,0.184517,0.018850,0.007689,0.007627,poisson,sqrt,50,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.859162,0.796549,0.808645,0.829658,0.769978,0.812799,0.030162,2
32,0.314160,0.077199,0.009450,0.007996,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.863668,0.787195,0.812182,0.822199,0.771570,0.811363,0.031690,4
33,0.050808,0.015535,0.003126,0.006252,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.837307,0.789106,0.791059,0.776785,0.752837,0.789419,0.027546,10
34,0.201242,0.006294,0.003125,0.006249,poisson,log2,50,"{'criterion': 'poisson', 'max_features': 'log2...",0.850553,0.783539,0.817003,0.830899,0.770488,0.810496,0.029633,6
35,0.349292,0.009101,0.008406,0.002161,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.862938,0.794229,0.801475,0.826018,0.770516,0.811035,0.031414,5

In [16]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:32
BMI:28
Children:3
Sex Male 0 or 1:1
Smoker Yes 0 or 1:0

In [17]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print=("Future_prediction={}".format(Future_Prediction))

In [18]:
print

'Future_prediction=[16880.9792646]'